server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nicajonh/leyou-config
  rabbitmq:
    host: 99.6.118.187
    username: ga
    password: Gift@2018
    virtual-host: /mytest


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
